### ISSUE TITLE
unable to authorize when running as specified

### ISSUE THREAD

**Issue by damenk** [orcasgit/python-misfit#2]
So I successfully get everything installed via pip install misfit, and run the authorize command against my app, as specified.

It launches a browser and directs me to login.  I login, and am prompted to allow my app access to my profile.  I tell it to allow, but then I get "Error, unable to connect to remote host" - I am assuming the remote host is my server running the app itself... Not sure why I would not be able to connect, however.

![image](https://cloud.githubusercontent.com/assets/6218916/5989298/ddee617e-a937-11e4-85fe-4c539d100329.png)

**Comment by brad** [comment]
@damenk You are right, the remote host is your server. The authorize command starts up a CherryPy server on port 8080. What is this picture you've posted? It is unlike anything I've ever seen when running misfit commands. CherryPy outputs a lot of things and a successful authorize session should look somthing like this:
```
[31/Jan/2015:11:01:22] ENGINE Listening for SIGHUP.
[31/Jan/2015:11:01:22] ENGINE Listening for SIGTERM.
[31/Jan/2015:11:01:22] ENGINE Listening for SIGUSR1.
[31/Jan/2015:11:01:22] ENGINE Bus STARTING
CherryPy Checker:
The Application mounted at '' has an empty config.

[31/Jan/2015:11:01:22] ENGINE Started monitor thread 'Autoreloader'.
[31/Jan/2015:11:01:22] ENGINE Started monitor thread '_TimeoutMonitor'.
[31/Jan/2015:11:01:23] ENGINE Serving on http://127.0.0.1:8080
[31/Jan/2015:11:01:23] ENGINE Bus STARTED
ATTENTION: default value of option force_s3tc_enable overridden by environment.
Created new window in existing browser session.
127.0.0.1 - - [31/Jan/2015:11:01:25] "GET /?code=scrubbed&state=scrubbed HTTP/1.1" 200 122 "" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.93 Safari/537.36"
[31/Jan/2015:11:01:26] ENGINE Bus STOPPING
[31/Jan/2015:11:01:31] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('127.0.0.1', 8080)) shut down
[31/Jan/2015:11:01:31] ENGINE Stopped thread 'Autoreloader'.
[31/Jan/2015:11:01:31] ENGINE Stopped thread '_TimeoutMonitor'.
[31/Jan/2015:11:01:31] ENGINE Bus STOPPED
[31/Jan/2015:11:01:31] ENGINE Bus EXITING
[31/Jan/2015:11:01:31] ENGINE Bus EXITED
[31/Jan/2015:11:01:31] ENGINE Waiting for child threads to terminate...
Credentials written to ./misfit.cfg
```

**Comment by damenk** [comment]
not that, lol.

When I run the misfit command, it launches a browser (lynx, in this case), which takes me to a page to login.  I login, it then says "hey, your app wants access to your profile!  Allow/ Dont Allow"

I hit "allow"

then I get what I posted before

I will re-post with more of the surrounding screen here now:

![image](https://cloud.githubusercontent.com/assets/6218916/5989437/10e2e3c0-a93d-11e4-88a1-d3bac5dbe326.png)

![image](https://cloud.githubusercontent.com/assets/6218916/5989440/2cd4e2fe-a93d-11e4-90fd-08fb594d1312.png)

**Comment by brad** [comment]
@damenk That is super cool to see it happen through Lynx! If you are unable to browse to http://127.0.0.1:8080 while the CherryPy server is running, then it sounds like port 8080 may be blocked by a local firewall. Maybe try stopping iptables just for the duration of the authorization?

**Comment by damenk** [comment]
no difference, I'm afraid.  iptables wasnt running, but I uninstalled it entirely from the server for good measure :(

**Comment by brad** [comment]
OK, I managed to reproduce the problem in lynx or elinks. Thank you for the bug report, I will work on it. In the meantime, it should work just fine if you can run it from a desktop with a GUI browser.

**Comment by brad** [comment]
@damenk Please update to misfit==0.2.0, it should work now.

**Comment by damenk** [comment]
success! thanks :)

**Comment by brad** [comment]
No problem, glad to hear! :+1:
